export const ActionTypes = {
  SET_TWEETS: "SET_TWEETS",
  SET_TWEETLIKES: "SET_TWEETLIKES",
  SET_USERTWEETLIKES: "SET_USERTWEETLIKES",
  SET_TWEET_COMMENTS: "SET_TWEET_COMMENTS",
  SET_PROFILE: "SET_PROFILE",
  SET_UPDATED_TWEETS: "SET_UPDATED_TWEETS",
  SET_DELETED_TWETS: " SET_DELETED_TWETS:",
};
